### ISSUE TITLE
ModuleNotFoundError: No module named 'wget' (undeclared dependency?)

### ISSUE THREAD

**Issue by boronine** [zafercavdar/fasttext-langdetect#4] opened 2021-11-26 08:29 UTC
macOS on M1 (aarch64), Python 3.8.9

```
(venv) alexei@m1 heftoscms % python3
Python 3.8.9 (default, Aug  3 2021, 19:21:54) 
[Clang 13.0.0 (clang-1300.0.29.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from ftlangdetect import detect
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/alexei/Heftos/heftoscms/venv/lib/python3.8/site-packages/ftlangdetect/__init__.py", line 1, in <module>
    from .detect import detect
  File "/Users/alexei/Heftos/heftoscms/venv/lib/python3.8/site-packages/ftlangdetect/detect.py", line 5, in <module>
    import wget
ModuleNotFoundError: No module named 'wget'
```

After `pip install wget` the problem went away. Probably need to declare the dependency.

**Comment by hyper750** [comment] 2022-07-29 09:37
The problem is `wget` is declared inside `requirements.txt` but not inside `setup.py >> install_requires`. This should fix it https://github.com/zafercavdar/fasttext-langdetect/pull/7

**Comment by zafercavdar** [comment] 2022-12-12 20:51
Fixed now.

**Closed by zafercavdar** 2022-12-12 20:52 UTC
